CA1_v2/Models/ErrorViewModel.cs
namespace CA1_v2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CA1_v2/Models/Match.cs
using System.ComponentModel.DataAnnotations;
using System.Xml.Linq;

namespace CA1_v2.Models
{
    public class Match
    {
        /*  NB Value types (such as decimal, int, float, DateTime) are inherently required (because they are non-null types)
         *   and don't need the [Required] attribute.
         *   If you want to make them NOT required make them nullable (e.g int?)
         */
        public int MatchID { get; set; }

        [Display(Name = "Match Date")]
        public DateTime MatchDate { get; set; }

        [Required]
        [StringLength(maximumLength: 100, MinimumLength = 2)]
        public string Opponent { get; set; } = "";

        [Required]
        [StringLength(maximumLength: 100, MinimumLength = 2)]
        public string Venue { get; set; } = "";


        //I've used int? below to enure Goals for and Goals agaist are not required 
        //If i used int, it means they are required

        [Display(Name = "Goals For")]
        [Range(0, 50, ErrorMessage = "Max number of goals allowed is 50")]
        public int? GoalsFor { get; set; }


        [Display(Name = "Goals Against")]
        [Range(0, 50, ErrorMessage = "Max number of goals allowed is 50")]
        public int? GoalsAgainst { get; set; }
    }
}

CA1_v2/Models/Stats.cs
using CA1_v2.Repository;

namespace CA1_v2.Models
{
    public class Stats 
    {
        public IEnumerable<Match> matches;
        public int Won { get; set; }
        public int Lost { get; set; }
        public int Drew { get; set; }
        public int Points { get; set; }
        public int GoalDiff { get; set; }

        public Stats(IMatchRepo m)
        {
            matches = m.GetFixtures();
            IEnumerable<Match> PlayedMatches = matches.Where(p => p.MatchDate < DateTime.Today.Date);
            Won = PlayedMatches.Where(p => (p.GoalsFor > p.GoalsAgainst)).ToList().Count;
            Lost = PlayedMatches.Where(p => (p.GoalsFor < p.GoalsAgainst)).ToList().Count;
            Drew = PlayedMatches.Where(p => (p.GoalsFor == p.GoalsAgainst)).ToList().Count;
            Points = PlayedMatches.Select(p =>
            {
                if (p.GoalsFor > p.GoalsFor) return 3; //Win
                if (p.GoalsFor == p.GoalsFor) return 1; //Draw
                return 0;                              //Lose                                            
            }).Sum();                                //Now sum list of ints
            //GoalDiff = (PlayedMatches.Sum(p => p.GoalsFor)) - (PlayedMatches.Sum(p => p.GoalsAgainst));

        }


    }
}

CA1_v2/Controllers/HomeController.cs
using CA1_v2.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CA1_v2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CA1_v2/Controllers/MatchesController.cs
using CA1_v2.Models;
using CA1_v2.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Security.Cryptography.X509Certificates;

namespace CA1_v2.Controllers
{
    public class MatchesController : Controller
    {
        IMatchRepo _repo;

        public MatchesController(IMatchRepo repo)
        {
            _repo = repo;
        }


        // GET: MatchesController
        public ActionResult Index()
        {
            var matches = _repo.GetFixtures();
            return View(matches);
        }

        public ActionResult GetStats()
        {
            Stats allMatches = new Stats(_repo);
            return View(allMatches);
        }

        // GET: MatchesController/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: MatchesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MatchesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Match m)
        {
            try
            {
                if(ModelState.IsValid)
                {
                    _repo.CreateFixture(m);
                    return RedirectToAction(nameof(Index));

                }
                return View();
                
            }
            catch
            {
                return View();
            }
        }

        // GET: MatchesController/Edit/5
        public ActionResult Edit(int id)
        {
            var match = _repo.GetFixture(id);
            return View(match);
        }

        // POST: MatchesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Match m)
        {
            try
            {
                _repo.EditFixture(m);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: MatchesController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MatchesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CA1_v2/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

CA1_v2/Views/Matches/Create.cshtml
@model CA1_v2.Models.Match

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Match</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MatchID" class="control-label"></label>
                <input asp-for="MatchID" class="form-control" />
                <span asp-validation-for="MatchID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatchDate" class="control-label"></label>
                <input asp-for="MatchDate" class="form-control" />
                <span asp-validation-for="MatchDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opponent" class="control-label"></label>
                <input asp-for="Opponent" class="form-control" />
                <span asp-validation-for="Opponent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            @*
            <div class="form-group">
            <label asp-for="GoalsFor" class="control-label"></label>
            <input asp-for="GoalsFor" class="form-control" />
            <span asp-validation-for="GoalsFor" class="text-danger"></span>
            </div>
            <div class="form-group">
            <label asp-for="GoalsAgainst" class="control-label"></label>
            <input asp-for="GoalsAgainst" class="form-control" />
            <span asp-validation-for="GoalsAgainst" class="text-danger"></span>
            </div>
            *@
            
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CA1_v2/Views/Matches/Edit.cshtml
@model CA1_v2.Models.Match

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Match</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MatchID" class="control-label"></label>
                <input asp-for="MatchID" class="form-control" />
                <span asp-validation-for="MatchID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="MatchDate" class="control-label"></label>
                <input asp-for="MatchDate" class="form-control" />
                <span asp-validation-for="MatchDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Opponent" class="control-label"></label>
                <input asp-for="Opponent" class="form-control" />
                <span asp-validation-for="Opponent" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Venue" class="control-label"></label>
                <input asp-for="Venue" class="form-control" />
                <span asp-validation-for="Venue" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GoalsFor" class="control-label"></label>
                <input asp-for="GoalsFor" class="form-control" />
                <span asp-validation-for="GoalsFor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GoalsAgainst" class="control-label"></label>
                <input asp-for="GoalsAgainst" class="form-control" />
                <span asp-validation-for="GoalsAgainst" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CA1_v2/Views/Matches/GetStats.cshtml
@model CA1_v2.Models.Stats

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Stats</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Won)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Won)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lost)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lost)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Drew)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Drew)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Points)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Points)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GoalDiff)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GoalDiff)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    <a asp-action="Index">Back to List</a>
</div>

CA1_v2/Views/Matches/Index.cshtml
@model IEnumerable<CA1_v2.Models.Match>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.MatchID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MatchDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Opponent)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Venue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GoalsFor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GoalsAgainst)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MatchID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MatchDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Opponent)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Venue)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GoalsFor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GoalsAgainst)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new {id = item.MatchID /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Details", "Details", new { item.MatchID /* id=item.PrimaryKey */ }) |
                @Html.ActionLink("Delete", "Delete", new { item.MatchID /* id=item.PrimaryKey */ })
            </td>
        </tr>
}
    </tbody>
</table>

CA1_v2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CA1_v2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/CA1_v2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CA1_v2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="Create">Create</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="Edit">Edit</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Matches" asp-action="GetStats">Stats</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CA1_v2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>